services:
  prometheus:
    image: prom/prometheus:v2.37.1
    hostname: prometheus
    configs:
      - source: prometheus-config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9099:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  node-exporter:
    image: nginx
    configs:
      - source: nodeexpoter-config
        target: /etc/nginx/nginx.conf
    deploy:
      mode: global

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   # hostname: '{{.Node.Hostname}}' # Use the node's hostname for easier identification in Prometheus
  #   command:
  #     - "--path.rootfs=/rootfs"
  #     - "--path.procfs=/host/proc"
  #     - "--path.sysfs=/host/sys"
  #     - "--collector.filesystem.mount-points-exclude='^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/container|rootfs/var/lib/docker/overlay2|rootfs/var/lib/docker/aufs)($$|/)'"
  #   volumes:
  #     - /:/rootfs:ro,rslave # Bind mount the host's root filesystem
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #   deploy:
  #     mode: global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    # hostname: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

configs:
  prometheus-config:
    file: ./prometheus/prometheus.yml
  nodeexpoter-config:
    file: ./node_exporter_nginx.config

volumes:
  prometheus_data:
  grafana-storage: